config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  } 
  #ゲストログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  #ユーザー側ルート設定
  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about", as: :about
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: :followings
      get "followers" => "relationships#followers", as: :followers
      resources :likes, only: [:index] #ユーザーがいいねした一覧
    end
    get 'mypage' => 'users#mypage', as: :mypage
    resources :works do
      resources :comments, only: [:create, :destroy] do
        post "report" => "reports#report_comment", as: :report
      end
      resource :likes, only: [:create, :destroy]
      post "report" => "reports#report_work", as: :report
    end
    resources :notifications, only: [:index]
    get "search" => "searches#search", as: :search
    get "tags/:id" => "tags#search", as: :tag_search
    resources :chats, only: [:show, :create, :destroy] do
      post "report" => "reports#report_chat", as: :report
    end
  end
  
  #管理者側ルート設定
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update] do
      resources :rooms, only: [:index] do
        resources :chats, only: [:index]
      end
    end
    resources :works, only: [:show]
    resources :reports, only: [:index]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  
  belongs_to :reporter, class_name: "User"
  belongs_to :reported, class_name: "User"
  belongs_to :work, optional: true
  belongs_to :chat, optional: true
  belongs_to :comment, optional: true
  
  enum reason: { improper_work_post: 0, improper_chat: 1, improper_comment: 2 }
  
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @reports = Report.all.order(created_at: :desc)
  end
  
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 mx-auto">
      <h3>通報一覧</h3>
      <table class="table table-border">
        <tr>
          <th>対象者</th>
          <th>通報理由</th>
          <th>通報者</th>
          <th></th>
        </tr>
        <% @reports.each do |report| %>
          <tr>
            <td><%= report.reported.name %></td>
            <td><%= report.reason_i18n %></td>
            <td><%= report.reporter.name %></td>
            <td>
              <% if report.reason == "improper_work_post" %>
                <%= link_to '確認する＞', admin_work_path(report.work_id) %>
              <% elsif report.reason == "improper_chat" %>
                <%= link_to '確認する＞', admin_user_room_chats_path(report.reporter, report.chat.room_id) %>
              <% elsif report.reason == "improper_comment" %>
                <%= link_to '確認する＞', admin_work_path(report.comment.work_id) %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>