config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  } 
  #ゲストログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  #ユーザー側ルート設定
  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about", as: :about
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: :followings
      get "followers" => "relationships#followers", as: :followers
      resources :likes, only: [:index] #ユーザーがいいねした一覧
    end
    get 'mypage' => 'users#mypage', as: :mypage
    resources :works do
      resources :comments, only: [:create, :destroy] do
        post "report" => "reports#report_comment", as: :report
      end
      resource :likes, only: [:create, :destroy]
      post "report" => "reports#report_work", as: :report
    end
    resources :notifications, only: [:index]
    get "search" => "searches#search", as: :search
    get "tags/:id" => "tags#search", as: :tag_search
    resources :chats, only: [:show, :create, :destroy] do
      post "report" => "reports#report_chat", as: :report
    end
  end
  
  #管理者側ルート設定
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update] do
      resources :rooms, only: [:index] do
        resources :chats, only: [:index]
      end
    end
    resources :works, only: [:show]
    resources :reports, only: [:index]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true, length: { maximum: 20 }
  validates :introduction, length: { maximum: 100 } 
  
  has_many :works, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :view_counts
  
  has_many :likes, dependent: :destroy
  has_many :like_works, through: :likes, source: :work
  
  #DM機能
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms
 
 #与フォローの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  #被フォローの関係
  has_many :reverse_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  
  #通知機能
  has_many :notifications, class_name: "Notification", foreign_key: "visitor_id", dependent: :destroy
  has_many :reverse_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy
  
  #通報機能
  has_many :reports, class_name: "Report", foreign_key: "reporter_id", dependent: :destroy
  has_many :reverse_reports, class_name: "Report", foreign_key: "reported_id", dependent: :destroy
  
  has_one_attached :profile_image
  
  GUEST_USER_EMAIL = "guest@example.com"
  #ゲストユーザーログイン
  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  #ゲストユーザーではない=>TRUE
  def not_guest
    email != GUEST_USER_EMAIL
  end
  
  #デフォルト画像の設定
  def upload_default_profile_image
    file_path = Rails.root.join("app/assets/images/no_image.jpg")
    profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
  end
  
  def get_profile_image(width, height)
    upload_default_profile_image unless profile_image.attached?
    profile_image.variant(resize: "#{width}x#{height}^", gravity: "center", crop: "#{width}x#{height}+0+0").processed
  end
  
  def follow(user)
    relationships.create(followed_id: user.id)
  end
  
  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  def create_notification_follow(current_user)
    #一度通知したものは通知しない
    unless Notification.where(visitor_id: current_user, visited_id: id, action: "follow").present?
      @notification = current_user.notifications.new(
        visited_id: id,
        action: 3
        )
      @notification.save
    end
  end
  
  def have_unread_notification?
    notifications = Notification.where(visited_id: id)
    notifications.find_by(checked: false).present?
  end
  
  def self.search(word)
    self.where("name LIKE?", "%#{word}%")
  end 
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_path(user)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:is_active)
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 mx-auto">
      <%= form_with model: @user, url: admin_user_path(@user), local: true do |f| %>
        <table class="table table-borderless">
          <tr>
            <th class="text-right pr-3">プロフィール画像：</th>
            <td><%= image_tag @user.get_profile_image(40,40) %></td>
          </tr>
          <tr>
            <th class="text-right pr-3">名前：</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th class="text-right pr-3">自己紹介：</th>
            <td><%= @user.introduction %></td>
          </tr>
          <tr>
            <th class="text-right pr-3">アカウント停止ステータス：</th>
            <td>
              <span class="mr-3">
                <%= f.radio_button :is_active, true %>
                <%= f.label :is_active, '有効', value: true, class:"m-0" %>
              </span>
              <span>
                <%= f.radio_button :is_active, false %>
                <%= f.label :is_active, '停止', value: false, class:"m-0" %>
              </span>
            </td>
          </tr>
        </table>
        <div class="text-center"><%= f.submit '更新する' %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 mx-auto">
      <table class="table">
        <% @users.each do |user| %>
          <tr>
            <td class="p-1">
              <%= image_tag user.get_profile_image(40,40), class:"rounded-circle" %>
            </td>
            <td>
              <%= user.name %>
              <div class="text-danger">
                <% if user.is_active == false %>
                  アカウント停止中
                <% end %>
              </div>
            </td>
            <td>投稿数: <%= user.works.count %></td>
            <td>被通報数: <%= user.reverse_reports.count %></td>
            <td><%= link_to '詳細', admin_user_path(user) %></td>
            <td><%= link_to 'チャット一覧', admin_user_rooms_path(user) %></td>
            <td><%= link_to '編集', edit_admin_user_path(user) %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h4>ユーザー詳細</h4>
      <div class="card p-1">
        <div>
          <%= image_tag @user.get_profile_image(70,70), class:"rounded-circle p-2" %>
          <strong><%= @user.name %></strong>
        </div>
        <div class="text-danger">
          <% if @user.is_active == false %>
            アカウント停止中です
          <% end %>
        </div>
        <div class="mt-4">
          <h5>自己紹介</h5>
          <div class="p-1"><%= @user.introduction %></div>
        </div>
      </div>
      <p class="mt-3">
        <%= link_to 'アカウントの停止 ＞', edit_admin_user_path(@user) %> 
      </p>
      <p>
        <%= link_to 'ユーザー一覧に戻る ＞', admin_users_path %>
      </p>
    </div>
    <div class="col-md-6 offset-1">
       <% @user.works.each do |work| %>
        <div class="card mb-3 w-100 shadow work-list">
          <div class="row no-gutters">
            <div class="col-md-4">
              <%= image_tag work.get_main_image(200, 200), class:"img-fluid" %>
            </div>
            <div class="col-md-5 mh-100">
              <div class="card-body">
                <h5 class="card-title mb-0"><%= work.title %></h5>
                <p class="card-text"><%= work.caption %></p>
                <p>
                  <%= link_to '詳細', admin_work_path(work), class:"text-link mx-1" %>
                </p>
              </div>
            </div>
            <div class="col-md-3">
              <div class="card-body">
                <p class="car-text"><small>
                いいね：<%= work.likes.count %></br>
                コメント数：<%= work.comments.count %></br>
                </small></p>
                <p class="card-text"><small class="text-muted">投稿日：<%= work.created_at.strftime('%Y/%m/%d') %></small></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>