config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  
  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  } 
  #ゲストログイン
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  
  #ユーザー側ルート設定
  scope module: :public do
    root to: "homes#top"
    get "about" => "homes#about", as: :about
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: :followings
      get "followers" => "relationships#followers", as: :followers
      resources :likes, only: [:index] #ユーザーがいいねした一覧
    end
    get 'mypage' => 'users#mypage', as: :mypage
    resources :works do
      resources :comments, only: [:create, :destroy] do
        post "report" => "reports#report_comment", as: :report
      end
      resource :likes, only: [:create, :destroy]
      post "report" => "reports#report_work", as: :report
    end
    resources :notifications, only: [:index]
    get "search" => "searches#search", as: :search
    get "tags/:id" => "tags#search", as: :tag_search
    resources :chats, only: [:show, :create, :destroy] do
      post "report" => "reports#report_chat", as: :report
    end
  end
  
  #管理者側ルート設定
  namespace :admin do
    root to: "homes#top"
    resources :users, only: [:index, :show, :edit, :update] do
      resources :rooms, only: [:index] do
        resources :chats, only: [:index]
      end
    end
    resources :works, only: [:show]
    resources :reports, only: [:index]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_message.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger m-4">
    <h5>以下のエラーが発生しました。</h5>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="bg-dark w-100 p-4 text-light">
  <div class="container">
    <div class="row text-center mx-auto">
      <p class="w-100">copywright moke moke</p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container pb-2">
    
    <div>
      <% if admin_signed_in? %>
        <%= link_to '管理者ページ', admin_root_path, class:"navbar-brand" %>
      <% elsif user_signed_in? %>
        <%= link_to works_path, class:"navbar-brand" do %>
          <%= image_tag 'navbar_logo.png', size:"118x80" %>
        <% end %>
      <% else %>
        <%= link_to root_path, class:"navbar-brand" do %>
          <%= image_tag 'navbar_logo.png', size:"118x80" %>
        <% end %>
      <% end %>
    </div>
    <!--ナビゲーションバー-->
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto h5">
        
        <% if user_signed_in? %>
          <li class="nav-item text-right">
            <%= link_to "マイページ", mypage_path, class:"nav-link" %>
          </li>
          <li class="nav-item text-right">
            <%= link_to "投稿する", new_work_path, class:"nav-link" %>
          </li>
          <li class="nav-item text-right">
            <%= link_to "投稿一覧", works_path, class:"nav-link" %>
          </li>
          <li class="nav-item text-right">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
          
        <% elsif admin_signed_in? %>
          <li class="nav-item text-right">
            <%= link_to "ユーザー管理", admin_users_path, class:"nav-link" %>
          </li>
          <li class="nav-item text-right">
            <%= link_to "通報一覧", admin_reports_path, class:"nav-link" %>
          </li>
          <li class="nav-item text-right">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"nav-link" %>
          </li>
          
        <% else %>
          <li class="nav-item text-right">
            <%= link_to "ホーム", root_path, class:"nav-link" %>
          </li>
          <li class="nav-item text-right">
            <%= link_to "もけ×もけとは", about_path, class:"nav-link" %>
          </li>
          <li class="nav-item text-right">
            <%= link_to "新規登録", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item text-right">
            <%= link_to "ログイン", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
      <!--検索フォーム-->
      <div>
        <%= render 'public/searches/form' %>
      </div>
    </div>
      
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MokeMoke</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>

    <script src="https://kit.fontawesome.com/f9ffc047f5.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <main class="py-3">
      <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>